### ISSUE TITLE
Synchronisation des données avec des bases de données externes

### ISSUE THREAD

**Issue by Marc-AntoineA** [JulienRobberechts/memo-fresque-du-climat#8]
Un des enjeux de ce projet est d'avoir des **textes corrects et à jour**. 
Or, en l'état, c'est une copie manuelle issue de différents documents, avec des données non synchronisées dans les sources existantes. Si demain un·e animateurice corrige le wiki, cette information ne sera pas présente dans l'application. 

Est-ce qu'on ne pourrait pas connecter l'outil au wiki de la fresque (la synchronisation peut ne pas être instantanée mais peut être réalisée tous les X jours / semaines) ? Ou alors est-ce que le wiki aura encore un intérêt ?

**Comment by JulienRobberechts** [comment]
Bonne observation et bonne question. Dans l'état actuel des choses le Wiki ne contient pas toute les informations à jour (et je n'ai pas les droits pour les modifier) et deuxièmement le wiki n'est pas assez structurer (pour l'instant) pour que toute les données soit récupérées du Wiki. Pour info j'ai utilisé l'API WikiMedia pour récupérer les cartes et les liens de base mais ensuite j'ai du abandonner cette approche automatique car tout n'est pas à jour.

Peut-être que si on modifie le wiki (en structure et donnés) ça peut devenir le repo de donnés de référence.

**Comment by JulienRobberechts** [comment]
c'est en cours dans ce projet: https://github.com/JulienRobberechts/climate-collage-wiki-scraping

**Comment by JulienRobberechts** [comment]
La première importation manuelle a été faite. c'est tellement sensible qu'il faut mieux garder ça manuelle.
